name: 02-Worker-Join
on: 
  workflow_dispatch: # 手動觸發

jobs:
  join-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Join Worker to K3s Cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WORKER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          steps:
      - name: Join K3s Worker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WORKER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # 1. 把 GitHub 的 Secret 餵進來
          envs: K3S_TOKEN_MASTER, MASTER_IP
          script: |
            # 2. 補齊 iptables (EL10/EL9 必需)
            dnf install -y iptables iptables-services
            
            # 3. 改名 (確保在安裝前完成，身分才不會錯)
            hostnamectl set-hostname k3s-worker-01
            
            # 4. 連上 Master
            # 直接使用 envs 傳進來的變數
            export K3S_URL="https://${MASTER_IP}:6443"
            export K3S_TOKEN="${K3S_TOKEN_MASTER}"


            curl -sfL https://get.k3s.io | sh -
            
            # 5. 驗證狀態
            systemctl is-active --quiet k3s-agent && echo " k3s-worker-01 Joined Successfully!"